export interface MetronomeSound {
  id: string;
  name: string;
  category: string;
  hi: number; // require() asset ID
  lo: number;
}

export const METRONOME_SOUNDS: MetronomeSound[] = [
  // Percussion
  { id: 'Perc_MetronomeQuartz', name: 'Metronome Quartz', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_MetronomeQuartz_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_MetronomeQuartz_lo.wav') },
  { id: 'Perc_Stick', name: 'Stick', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Stick_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Stick_lo.wav') },
  { id: 'Perc_PracticePad', name: 'Practice Pad', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_PracticePad_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_PracticePad_lo.wav') },
  { id: 'Perc_Can', name: 'Can', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Can_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Can_lo.wav') },
  { id: 'Perc_Castanet', name: 'Castanet', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Castanet_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Castanet_lo.wav') },
  { id: 'Perc_Chair', name: 'Chair', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Chair_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Chair_lo.wav') },
  { id: 'Perc_Clackhead', name: 'Clackhead', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Clackhead_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Clackhead_lo.wav') },
  { id: 'Perc_Clap', name: 'Clap', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Clap_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Clap_lo.wav') },
  { id: 'Perc_ClickToy', name: 'Click Toy', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_ClickToy_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_ClickToy_lo.wav') },
  { id: 'Perc_Glass', name: 'Glass', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Glass_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Glass_lo.wav') },
  { id: 'Perc_HeadKnock', name: 'Head Knock', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_HeadKnock_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_HeadKnock_lo.wav') },
  { id: 'Perc_Keyboard', name: 'Keyboard', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Keyboard_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Keyboard_lo.wav') },
  { id: 'Perc_Metal', name: 'Metal', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Metal_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Metal_lo.wav') },
  { id: 'Perc_MouthPop', name: 'Mouth Pop', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_MouthPop_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_MouthPop_lo.wav') },
  { id: 'Perc_MusicStand', name: 'Music Stand', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_MusicStand_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_MusicStand_lo.wav') },
  { id: 'Perc_Snap', name: 'Snap', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Snap_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Snap_lo.wav') },
  { id: 'Perc_Squeak', name: 'Squeak', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Squeak_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Squeak_lo.wav') },
  { id: 'Perc_Tamb_A', name: 'Tambourine A', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Tamb_A_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Tamb_A_lo.wav') },
  { id: 'Perc_Tamb_B', name: 'Tambourine B', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Tamb_B_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Tamb_B_lo.wav') },
  { id: 'Perc_Tamb_C', name: 'Tambourine C', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Tamb_C_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Tamb_C_lo.wav') },
  { id: 'Perc_Tamb_D', name: 'Tambourine D', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Tamb_D_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Tamb_D_lo.wav') },
  { id: 'Perc_Teeth', name: 'Teeth', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Teeth_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Teeth_lo.wav') },
  { id: 'Perc_Tongue', name: 'Tongue', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_Tongue_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_Tongue_lo.wav') },
  { id: 'Perc_TrashCan', name: 'Trash Can', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_TrashCan_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_TrashCan_lo.wav') },
  { id: 'Perc_WhistleParty', name: 'Whistle Party', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_WhistleParty_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_WhistleParty_lo.wav') },
  { id: 'Perc_WhistleRef', name: 'Whistle Ref', category: 'Percussion',
    hi: require('@/assets/sounds/metronome/Perc_WhistleRef_hi.wav'),
    lo: require('@/assets/sounds/metronome/Perc_WhistleRef_lo.wav') },
  // Synth Bell
  { id: 'Synth_Bell_A', name: 'Bell A', category: 'Synth Bell',
    hi: require('@/assets/sounds/metronome/Synth_Bell_A_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Bell_A_lo.wav') },
  { id: 'Synth_Bell_B', name: 'Bell B', category: 'Synth Bell',
    hi: require('@/assets/sounds/metronome/Synth_Bell_B_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Bell_B_lo.wav') },
  // Synth Block
  { id: 'Synth_Block_A', name: 'Block A', category: 'Synth Block',
    hi: require('@/assets/sounds/metronome/Synth_Block_A_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Block_A_lo.wav') },
  { id: 'Synth_Block_B', name: 'Block B', category: 'Synth Block',
    hi: require('@/assets/sounds/metronome/Synth_Block_B_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Block_B_lo.wav') },
  { id: 'Synth_Block_C', name: 'Block C', category: 'Synth Block',
    hi: require('@/assets/sounds/metronome/Synth_Block_C_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Block_C_lo.wav') },
  { id: 'Synth_Block_D', name: 'Block D', category: 'Synth Block',
    hi: require('@/assets/sounds/metronome/Synth_Block_D_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Block_D_lo.wav') },
  { id: 'Synth_Block_E', name: 'Block E', category: 'Synth Block',
    hi: require('@/assets/sounds/metronome/Synth_Block_E_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Block_E_lo.wav') },
  { id: 'Synth_Block_F', name: 'Block F', category: 'Synth Block',
    hi: require('@/assets/sounds/metronome/Synth_Block_F_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Block_F_lo.wav') },
  { id: 'Synth_Block_G', name: 'Block G', category: 'Synth Block',
    hi: require('@/assets/sounds/metronome/Synth_Block_G_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Block_G_lo.wav') },
  { id: 'Synth_Block_H', name: 'Block H', category: 'Synth Block',
    hi: require('@/assets/sounds/metronome/Synth_Block_H_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Block_H_lo.wav') },
  // Synth Sine
  { id: 'Synth_Sine_A', name: 'Sine A', category: 'Synth Sine',
    hi: require('@/assets/sounds/metronome/Synth_Sine_A_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Sine_A_lo.wav') },
  { id: 'Synth_Sine_B', name: 'Sine B', category: 'Synth Sine',
    hi: require('@/assets/sounds/metronome/Synth_Sine_B_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Sine_B_lo.wav') },
  { id: 'Synth_Sine_C', name: 'Sine C', category: 'Synth Sine',
    hi: require('@/assets/sounds/metronome/Synth_Sine_C_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Sine_C_lo.wav') },
  { id: 'Synth_Sine_D', name: 'Sine D', category: 'Synth Sine',
    hi: require('@/assets/sounds/metronome/Synth_Sine_D_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Sine_D_lo.wav') },
  { id: 'Synth_Sine_E', name: 'Sine E', category: 'Synth Sine',
    hi: require('@/assets/sounds/metronome/Synth_Sine_E_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Sine_E_lo.wav') },
  { id: 'Synth_Sine_F', name: 'Sine F', category: 'Synth Sine',
    hi: require('@/assets/sounds/metronome/Synth_Sine_F_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Sine_F_lo.wav') },
  // Synth Square
  { id: 'Synth_Square_A', name: 'Square A', category: 'Synth Square',
    hi: require('@/assets/sounds/metronome/Synth_Square_A_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Square_A_lo.wav') },
  { id: 'Synth_Square_B', name: 'Square B', category: 'Synth Square',
    hi: require('@/assets/sounds/metronome/Synth_Square_B_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Square_B_lo.wav') },
  { id: 'Synth_Square_C', name: 'Square C', category: 'Synth Square',
    hi: require('@/assets/sounds/metronome/Synth_Square_C_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Square_C_lo.wav') },
  { id: 'Synth_Square_D', name: 'Square D', category: 'Synth Square',
    hi: require('@/assets/sounds/metronome/Synth_Square_D_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Square_D_lo.wav') },
  { id: 'Synth_Square_E', name: 'Square E', category: 'Synth Square',
    hi: require('@/assets/sounds/metronome/Synth_Square_E_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Square_E_lo.wav') },
  // Synth Tick
  { id: 'Synth_Tick_A', name: 'Tick A', category: 'Synth Tick',
    hi: require('@/assets/sounds/metronome/Synth_Tick_A_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Tick_A_lo.wav') },
  { id: 'Synth_Tick_B', name: 'Tick B', category: 'Synth Tick',
    hi: require('@/assets/sounds/metronome/Synth_Tick_B_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Tick_B_lo.wav') },
  { id: 'Synth_Tick_C', name: 'Tick C', category: 'Synth Tick',
    hi: require('@/assets/sounds/metronome/Synth_Tick_C_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Tick_C_lo.wav') },
  { id: 'Synth_Tick_D', name: 'Tick D', category: 'Synth Tick',
    hi: require('@/assets/sounds/metronome/Synth_Tick_D_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Tick_D_lo.wav') },
  { id: 'Synth_Tick_E', name: 'Tick E', category: 'Synth Tick',
    hi: require('@/assets/sounds/metronome/Synth_Tick_E_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Tick_E_lo.wav') },
  { id: 'Synth_Tick_F', name: 'Tick F', category: 'Synth Tick',
    hi: require('@/assets/sounds/metronome/Synth_Tick_F_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Tick_F_lo.wav') },
  { id: 'Synth_Tick_G', name: 'Tick G', category: 'Synth Tick',
    hi: require('@/assets/sounds/metronome/Synth_Tick_G_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Tick_G_lo.wav') },
  { id: 'Synth_Tick_H', name: 'Tick H', category: 'Synth Tick',
    hi: require('@/assets/sounds/metronome/Synth_Tick_H_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Tick_H_lo.wav') },
  // Synth Weird
  { id: 'Synth_Weird_A', name: 'Weird A', category: 'Synth Weird',
    hi: require('@/assets/sounds/metronome/Synth_Weird_A_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Weird_A_lo.wav') },
  { id: 'Synth_Weird_B', name: 'Weird B', category: 'Synth Weird',
    hi: require('@/assets/sounds/metronome/Synth_Weird_B_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Weird_B_lo.wav') },
  { id: 'Synth_Weird_C', name: 'Weird C', category: 'Synth Weird',
    hi: require('@/assets/sounds/metronome/Synth_Weird_C_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Weird_C_lo.wav') },
  { id: 'Synth_Weird_D', name: 'Weird D', category: 'Synth Weird',
    hi: require('@/assets/sounds/metronome/Synth_Weird_D_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Weird_D_lo.wav') },
  { id: 'Synth_Weird_E', name: 'Weird E', category: 'Synth Weird',
    hi: require('@/assets/sounds/metronome/Synth_Weird_E_hi.wav'),
    lo: require('@/assets/sounds/metronome/Synth_Weird_E_lo.wav') },
];

export const DEFAULT_SOUND_ID = 'Perc_MetronomeQuartz';

/** Get unique categories in display order */
export function getSoundCategories(): string[] {
  const seen = new Set<string>();
  const categories: string[] = [];
  for (const s of METRONOME_SOUNDS) {
    if (!seen.has(s.category)) {
      seen.add(s.category);
      categories.push(s.category);
    }
  }
  return categories;
}

/** Get sounds for a specific category */
export function getSoundsForCategory(category: string): MetronomeSound[] {
  return METRONOME_SOUNDS.filter((s) => s.category === category);
}

/** Find a sound by ID, falling back to default */
export function getSoundById(id: string): MetronomeSound {
  return METRONOME_SOUNDS.find((s) => s.id === id) ?? METRONOME_SOUNDS[0];
}
